services:
  postgres:
    image: postgres:16
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5434:5432"
    networks:
      - keycloak_network


  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev
    environment:
      KC_LOG_LEVEL: debug
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      # Enable Remote Debugging
      JAVA_OPTS_APPEND: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./opt/keycloak/data/:/opt/keycloak/data
      - ./opt/keycloak/providers/:/opt/keycloak/providers
      - ./opt/keycloak/themes/:/opt/keycloak/themes
      - ./../target/crowd-user-storage.jar:/opt/keycloak/providers/crowd-user-storage.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
  
networks:
  keycloak_network:
    driver: bridge